name: Generate Javadocs
# Run this workflow once the site/data/variables.yaml file has been updated
on:
  push:
    paths:
    - 'site/data/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven

    - name: Save checkout tags for sdk-platform-java, google-cloud-java, and handwritten libraries
      id: save-tags
      run: |
        SDK_PLATFORM_JAVA="google-cloud-shared-dependencies"
        GOOGLE_CLOUD_JAVA="gapic-libraries-bom"
        VARIABLES_FILE="site/data/variables.yaml"

        SDK_PLATFORM_JAVA_TAG=$(grep -oP "(?<=${SDK_PLATFORM_JAVA}: \")[^\"]*" "$VARIABLES_FILE" | tr -d '\n')
        echo "SDK_PLATFORM_JAVA_TAG=$SDK_PLATFORM_JAVA_TAG" >> $GITHUB_ENV

        GOOGLE_CLOUD_JAVA_TAG=$(grep -oP "(?<=${SDK_PLATFORM_JAVA}: \")[^\"]*" "$VARIABLES_FILE" | tr -d '\n')
        echo "GOOGLE_CLOUD_JAVA_TAG=$GOOGLE_CLOUD_JAVA_TAG" >> $GITHUB_ENV

    - name: Generate javadocs for modules within sdk-platform-java repo
      run: |
        git clone https://github.com/googleapis/sdk-platform-java.git
        git -C sdk-platform-java checkout google-cloud-shared-dependencies/${{ env.SDK_PLATFORM_JAVA_TAG }}
        cd sdk-platform-java
        while read -r artifact directory
        do
          echo "ARTIFACT=$artifact"
          echo "DIRECTORY=$directory"
          echo "Creating and clearing directory for javadocs for ${artifact}"
          mkdir -p ../site/static/${artifact} # Make sure the output directory exists
          rm -rf ../site/static/${artifact}/ # Clear any existing files in the output directory
          echo "Generating javadocs for ${artifact}"
          mvn -f ${directory}/pom.xml javadoc:aggregate -Dmaven.javadoc.failOnError=false && mv ${directory}/target/site/apidocs/ ../site/static/${artifact}/
        done < ../.github/workflows/javadocs_scripts/sdk-platform-java_javadocs_modules.txt

    - name: Generate javadocs for modules within google-cloud-java repo
      run: |
        git clone https://github.com/googleapis/google-cloud-java.git
        git -C google-cloud-java checkout ${{ env.GOOGLE_CLOUD_JAVA_TAG }}
        while read -r artifact directory
        do
          echo "ARTIFACT=$artifact"
          echo "DIRECTORY=$directory"
          echo "Creating and clearing directory for javadocs for ${artifact}"
          mkdir -p ../site/static/${artifact} # Make sure the output directory exists
          rm -rf ../site/static/${artifact}/ # Clear any existing files in the output directory
          echo "Generating javadocs for ${artifact}"
          mvn -f ${directory}/pom.xml javadoc:aggregate -Dmaven.javadoc.failOnError=false && mv ${directory}/target/site/apidocs/ ../site/static/${artifact}/
        done < ../.github/workflows/javadocs_scripts/google-cloud-java_javadocs_modules.txt

    - name: Commit Javadocs
      run: |
        git -C site/static/ add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add Javadocs for sdk-platform-java and google-cloud-java modules" -a || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ github.token }}