name: Generate Javadocs
# Run this workflow once the site/data/variables.yaml file has been updated
on:
  push:
    paths:
    - 'site/data/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven

    - name: Save checkout tags for sdk-platform-java, google-cloud-java, and handwritten libraries
      id: save-tags
      run: |
        SDK_PLATFORM_JAVA_TAG="google-cloud-shared-dependencies"
        VARIABLES_FILE="site/data/variables.yaml"

        sdkplatformjavatag=$(grep -oP "(?<=${SDK_PLATFORM_JAVA_TAG}: \")[^\"]*" "$VARIABLES_FILE" | tr -d '\n')
        echo "::set-output name=sdkplatformjavatag::$sdkplatformjavatag

    - name: Create or clear directories for the javadocs
      run: |
        mkdir -p site/static/google-cloud-bigquery # Make sure the output directory exists
        rm -rf site/static/google-cloud-bigquery/*  # Clear any existing files in the output directory

    - name: Generate javadocs for modules within sdk-platform-java repo
      run: |
        git clone https://github.com/googleapis/sdk-platform-java.git
        git -C sdk-platform-java checkout google-cloud-shared-dependencies${{ steps.save-tags.outputs.sdkplatformjavatag }}
        while read -r artifact directory
        do
          echo "ARTIFACT=$artifact"
          echo "DIRECTORY=$directory"
          echo "Creating and clearing directory for javadocs for ${artifact}"
          mkdir -p site/static/${artifact} # Make sure the output directory exists
          rm -rf site/static/${artifact}/ # Clear any existing files in the output directory
          echo "Generating javadocs for ${artifact}"
          mvn -f ${directory}/pom.xml javadoc:aggregate -Dmaven.javadoc.failOnError=false && mv ${directory}/target/site/apidocs/ site/static/${artifact}/
        done < .github/workflows/javadocs_scripts/sdk-platform-java_javadocs_modules.txt

    - name: Commit Javadocs
      run: |
        git -C site/static/ add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add Javadocs for sdk-platform-java modules" -a || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ github.token }}