name: Generate Javadocs

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven

    - name: Create or clear directories for the javadocs
      run: |
        mkdir -p site/static/google-cloud-bigquery # Make sure the output directory exists
        rm -rf site/static/google-cloud-bigquery/*  # Clear any existing files in the output directory

    - name: Manual checkout source and javadoc generation for testing purposes
      run: |
        git clone https://github.com/googleapis/java-bigquery.git
        git -C java-bigquery checkout v2.26.0
        mvn -f google-cloud-bigquery/pom.xml javadoc:javadoc -Dmaven.javadoc.failOnError=false -Dmaven.javadoc.outputDirectory=/site/static/google-cloud-bigquery

    - name: Commit Javadocs
      run: |
        cd site/static
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add Javadocs for bigquery" -a || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ github.token }}